"""add guest recovery credentials

Revision ID: 27de3d72c81c
Revises: 1ec6166c3f35
Create Date: 2026-09-22 01:07:02.349212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27de3d72c81c'
down_revision: Union[str, Sequence[str], None] = '1ec6166c3f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_recovery_credentials',
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('credential_type', sa.String(length=16), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('credential_id'),
    sa.UniqueConstraint('secret_hash')
    )
    op.create_index(op.f('ix_guest_recovery_credentials_user_id'), 'guest_recovery_credentials', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guest_recovery_credentials_user_id'), table_name='guest_recovery_credentials')
    op.drop_table('guest_recovery_credentials')
    # ### end Alembic commands ###
